export * from "./home/home.component";
export * from "./register/register.component";
export * from "./login/login.component";
export * from "./me/me.component";
export * from "./about/about.component";
export * from "./posts/posts.component";
export * from "./posts/post/post.component";
export * from "./products/products.component";
export * from "./page-not-found/page-not-found.component";
